services:
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "4001:4001"
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkinpurry

  # redis:
  #   image: redis:latest
