services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
    ports:
      - "4001:4001"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      # - "5173:5173"
      - "3000:3000"
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkinpurry

  # redis:
  #   image: redis:latest
